## file location and name: # .github/workflows/docker-build.yml

##  Named of the workflow.
name: Python helloworld 

## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository

on: 
	push:
    	branches: [master]
  	pull_request:
    	branches: [master]

jobs:

	build:

    	runs-on: unbuntu-latest

    	steps:
      		-
        		name: Checkout
        		uses: actions/checkout@v2
      		-		
        		name: Set up QEMU
        		uses: docker/setup-qemu-action@v1
        	-
        		name: Set up  Docker Buildx
        		uses: docker/setup-buildx-action@v1
        	-
        		name: Login to DockerHub
        		uses: docker/login-action@v1
      			with:
        			username: ${{ secrets.DOCKERHUB_USERNAME}}
        			password: ${{ secrets.DOCKERHUB_TOKEN}}
        	-
      			name: Build and push
      			uses: docker/build-push-action@v2
      			with:
      			  context:
      			  	file: ./Dockerfile
      			  	platforms: linux/amd64
      			  	push: true
					tags: tbanj/python-helloworld:latest


                                                                                      